name: API Health Check

# Gatilhos que disparam a automação
on:
  schedule:
    - cron: '*/15 * * * *' # Executa a cada 15 minutos
  workflow_dispatch:        # Permite rodar manualmente no painel do GitHub

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer requisição para a API
        run: |
          HTTP_STATUS=$(curl -o /dev/null -s -w --header "Authorization: Basic bmV3QGZETmohNzVNOU1tSDo3STFsfGczPTlANkglUCtmdjVUbQ==" --location "https://wkrtswcddl.execute-api.us-east-2.amazonaws.com/vtex/rest/")
          echo "Status HTTP retornado: $HTTP_STATUS"
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "A API está fora do ar!"
            exit 1
          fi